[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "bash run.sh"
healthcheckPath = "/api/client/restaurants/"
restartPolicy = "on-failure"
maxRestartCount = 3
