[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "bash start_prod.sh"
healthcheckPath = "/health/"
restartPolicy = "on-failure"
maxRestartCount = 3
